title: Minor Notes
description: 一些想留下的筆記
lang: zh-Hant
timezone: Asia/Taipei
url: ""
baseurl: ""
permalink: /:categories/:year/:month/:day/:title/
markdown: kramdown

collections:
  posts:
    output: true

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
    values:
      layout: default
